#Custom Bundles
blog:
    resource: "@BlogBundle/Resources/config/routing.yml"
    prefix:   /

#FOSUserBundle
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    prefix:   /blog

#SonataAdminBundle
admin_area:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix: /blog/admin
