homepage:
    path:     /
    defaults: { _controller: BlogBundle:Info:index }

contact:
    path:     /contact
    defaults: { _controller: BlogBundle:Info:contact }

info:
    path:     /info
    defaults: { _controller: BlogBundle:Info:info }

blog:
    path:     /blog
    defaults: { _controller: BlogBundle:Blog:home }
